### ISSUE TITLE
Staff user interface inaccessible with plugin installed

### ISSUE THREAD

**Issue by jrcwiok** [dartmouth-dltg/local_contexts_projects#6]
Hello - We host a few ArchivesSpace sites that want to use the local contexts plugin. On v4.1.0, we installed the latest plugin and get the following errors - the staff side is in accessible with a message "Something went wrong". When we drop the plugin, the SUI is accessible. 
`98.4.45.216 - - [06/Jun/2025:18:15:29 +0000] "GET /favicon.ico HTTP/1.1" 404 675 "https://aspace-staff-dev.mit.edu/satff" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:139.0) Gecko/20100101 Firefox/139.0"
216.245.221.83 - - [06/Jun/2025:18:15:44 +0000] "GET / HTTP/1.1" 200 3571 "https://aspace-staff-dev.mit.edu/" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)"
F, [2025-06-06T14:15:49.078159 #109] FATAL -- :
ActionView::Template::Error (undefined method `[]' for #<ActionView::Base:0x00000000003740>):
    17:   <div class="col-md-6 col-xl-4 p-4 bg-light">
    18:     <main id="login-form-wrapper" class="card p-3 p-sm-4">
    19:       <h3 class="mt0"><%= I18n.t "login.login_please" %></h3>
    20:       <%= render_aspace_partial :partial => "shared/login" %>
    21:       <% if AppConfig[:allow_user_registration] %>
    22:         <p class="mb-2"><%= t "navbar.register_prefix" %> <%= link_to t("navbar.register"), {controller: "users", action: "new"}, class: "boring-link" %></p>
    23:       <% end %>

app/helpers/application_helper.rb:316:in `render_aspace_partial'
app/views/welcome/index.html.erb:20
app/controllers/application_controller.rb:761:in `set_locale'`

In this particular case, we had the following configurations:

`AppConfig[:local_contexts_api_key] = "redacted"
AppConfig[:local_contexts_base_url] = "https://sandbox.localcontextshub.org/" `

**Comment by jdshaw** [comment]
I had targeted the wrong branch for the release. Sorry about that! The v1.0.26 release should work with 4.1, but it does *not* include the EAD export changes related to `daogrp` made in 4.1 (https://github.com/archivesspace/archivesspace/commit/5be148e64f80a52d134469504d4412921f20bce2). That's on my ToDo list.
